### ISSUE TITLE
Delete Reminders 

### ISSUE THREAD

**Issue by pavelpark** [pavelpark/location-reminder#21]
Add table View for current reminders. Version 1.1

**Comment by robert-hatfield** [comment]
We could also use actionable UNNotifications:
[Managing Your App's Notification Support](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SupportingNotificationsinYourApp.html#//apple_ref/doc/uid/TP40008194-CH4-SW1)

I've started on this in c26746ad4338b3b6e4812ea414a4f5646b52d4a5 (branch `NotificationActions`).

**Comment by robert-hatfield** [comment]
Still to do:
- [x] Assign `UNUserNotificationCenterDelegate`
- [x] Add logic for `willPresentNotification`
- [x] Add logic for `didReceiveNotificationResponse`:
  - [x] `COMPLETE_ACTION`
  - [x] `SNOOZE_ACTION`

**Comment by robert-hatfield** [comment]
The initial code for `willPresentNotification` method has been built to handle notifications when the app is in the foreground. For now I've just got some logs to the console.

`didReceiveNotificationResponse` will handle the logic when the user selects a particular response.
