### ISSUE TITLE
Set limits on reminder radius

### ISSUE THREAD

**Issue by robert-hatfield** [pavelpark/location-reminder#43]
Radius should not be unreasonably high, and a lower limit may be advisable since location accuracy can sometimes be insufficient to fire off before the user is already outside of the region.

**Comment by pavelpark** [comment]
set upper limit to 40km, 40000 meters.
set lower limit to 15 meters.

**Comment by robert-hatfield** [comment]
Placeholder text with limit range is too long for the text fields. We'll be better off to add some small labels below the text fields when text is invalid.
